services:
  news-agreggator:
    build: .
    image: ruanaugustopasta/news-agreggator-react-challenge-test-local:latest
    volumes:
      - .:/app
      - /app/node_modules 
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
